import {Link} from "react-router-dom";import{useEffect,useState}from"react";import{overview}from"../api/api";import Illustration from"../components/Illustration";import Dropdown from"../components/Dropdown";
const demo=[
{title:"Water leakage",location:"Main Road • Block B",type:"water",status:"Urgent",text:"Continuous water leakage is affecting pedestrians and nearby shops.",image:"/images/civic-water-main.jpg"},
{title:"Water & sewer maintenance",location:"Urban service lane",type:"water",status:"High",text:"Field crews inspect and repair underground water infrastructure.",image:"https://media.jutarnji.hr/images/slike/2025/03/10/32948173.jpg"},
{title:"Garbage collection",location:"Community market",type:"waste",status:"High",text:"Sanitation teams collect waste and keep public spaces clean.",image:"https://www.starigrad.org.rs/wp-content/uploads/2024/10/WFL09995-cistoca-1024x683.jpg"},
{title:"Road repair",location:"Market Street",type:"road",status:"High",text:"Road crews repair damaged pavement to improve travel safety.",image:"https://www.antena3.ro/thumbs/big4/2026/02/06/primaria-capitalei-s-a-apucat-sa-repare-gropile-din-asfalt-pana-acum-s-au-gasit-585-pe-ce-strazi-sunt-lucrari-1044306.jpg"},
{title:"Street lighting",location:"Central Avenue",type:"lighting",status:"Medium",text:"Maintenance teams keep public lighting working across busy streets.",image:"https://portal-jalisco.s3.amazonaws.com/jalisco/original_images/_DSC0019.JPG"}
];
export default function Home(){const[s,setS]=useState({});const[filter,setFilter]=useState("all");useEffect(()=>{overview().then(r=>setS(r.data)).catch(()=>{})},[]);const cards=[["Total complaints",s.total||demo.length,"All submitted reports","blue"],["Open",s.open??demo.length,"Awaiting action","amber"],["Resolved",s.resolved||0,"Completed requests","green"],["Priority cases",s.high_critical??2,"Needs attention","red"]];const shown=filter==="all"?demo:demo.filter(x=>x.status.toLowerCase()===filter);return <><section className="hero"><div className="hero-copy"><span className="hero-kicker">SMARTER CIVIC RESPONSE</span><h1>See the problem.<br/><em>Understand the need.</em><br/>Act faster.</h1><p>CivicAI turns everyday citizen reports into organized cases, AI-assisted situation assessment and practical next steps.</p><div className="hero-actions"><Link className="btn primary" to="/submit">＋ Report an issue</Link><Link className="btn secondary" to="/dashboard">Explore insights →</Link></div><div className="hero-proof"><span>✦ AI-assisted</span><span>◉ Organized cases</span><span>↗ Faster response</span></div></div><div className="hero-art overview-photo-wrap"><div className="overview-photo-glow"/><div className="overview-photo-card"><img src="/images/civic-water-main.jpg" alt="Civic workers addressing a street infrastructure issue"/><div className="photo-overlay"><span className="photo-status"><span className="status-dot"/> Real civic service</span><strong>From problem to action</strong><small>Visualize the need. Report it. Route it.</small></div></div><span className="floating-card f1">● Live reports</span><span className="floating-card f2">✦ AI guidance</span></div></section>
<div className="quote-banner"><span className="quote-mark">“</span><div><p>When a civic problem is easy to report, understand and route, communities can respond before small issues become bigger ones.</p><small>CivicAI design principle</small></div></div>
<div className="section-heading"><div><span className="eyebrow">AT A GLANCE</span><h3>Service activity</h3></div><Dropdown label="View focus" items={["All services","Priority cases","Open cases"]}/></div><div className="metric-grid">{cards.map(([t,v,sub,c])=><div className="metric-card" key={t}><div className={'metric-icon '+c}>{t[0]}</div><div><span>{t}</span><strong>{v}</strong><small>{sub}</small></div></div>)}</div>
<div className="section-heading demo-head"><div><span className="eyebrow">DEMO CASES</span><h3>Common problems, clearly understood</h3></div><span className="muted-text">Sample data for presentation</span></div><div className="case-filter"><button className={filter==="all"?"active":""} onClick={()=>setFilter("all")}>All</button><button className={filter==="urgent"?"active":""} onClick={()=>setFilter("urgent")}>Urgent</button><button className={filter==="high"?"active":""} onClick={()=>setFilter("high")}>High</button></div><div className="case-grid">{shown.map(c=><div className="case-card photo-case" key={c.title}><div className="case-art photo-art"><img src={c.image} alt={c.title+" civic service"} loading="lazy" onError={e=>{e.currentTarget.style.display="none"}}/><div className="photo-art-fallback"><Illustration type={c.type}/></div><span className={'condition-badge '+c.status.toLowerCase()}>{c.status}</span><span className="field-chip">{c.type === "water" ? "Water & sanitation" : c.type === "waste" ? "Waste management" : c.type === "road" ? "Roads & transport" : "Public lighting"}</span></div><div className="case-body"><span className="case-location">⌖ {c.location}</span><h3>{c.title}</h3><p>{c.text}</p><Link to="/submit" className="feature-link">Report a similar issue →</Link></div></div>)}</div>
<div className="feature-grid"><Link to="/submit" className="feature-card featured"><span className="feature-number">01</span><h3>Describe the problem</h3><p>Use ordinary language. You do not need technical knowledge.</p><span className="feature-link">Start a report →</span></Link><Link to="/dashboard" className="feature-card"><span className="feature-number">02</span><h3>Understand the situation</h3><p>AI highlights likely condition, urgency and a practical first response.</p><span className="feature-link">See analytics →</span></Link><div className="feature-card"><span className="feature-number">03</span><h3>Connect action to impact</h3><p>Structured cases help teams prioritize work and track civic service performance.</p></div></div></>}
